environment:
    matrix:
        - TARGET: x86_64-pc-windows-msvc
        - TARGET: x86_64-pc-windows-gnu
        - TARGET: i686-pc-windows-msvc
        - TARGET: i686-pc-windows-gnu

before_install:
    - ps: |
        $SDL_VERSION = "2.0.5"
        $SDL_PREFIX = "C:\SDL\SDL2-$SDL_VERSION"
        if (!(Test-Path -Path $SDL_PREFIX)) {
            Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION-VC.zip
            7z x SDL2-devel-$SDL_VERSION-VC.zip -oC:\SDL\
        }
        $env:SDL2_INCLUDE = "$SDL_PREFIX\include"
        $env:SDL2_LIB = "$SDL_PREFIX\lib"

    - ps: |
        $SDL_TTF_VERSION = "2.0.1"
        $SDL_TTF_PREFIX = "C:\SDL\SDL2_ttf-$SDL_TTF_VERSION"
        if (!(Test-Path -Path $SDL_TTF_PREFIX)) {
            Start-FileDownload https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-$SDL_TTF_VERSION-VC.zip
            7z x SDL2_mixer-devel-$SDL_TTF_VERSION-VC.zip -oC:\SDL\
        }
        $env:SDL2_TTF_INCLUDE = "$SDL_TTF_PREFIX\include"
        $env:SDL2_TTF_LIB = "$SDL_TTF_PREFIX\lib"

    - ps: |
        $SDL_VERSION_M = "2.0.5"
        $SDL_PREFIX_M = "C:\SDL\SDL2M-$SDL_VERSION"
        if (!(Test-Path -Path $SDL_PREFIX_M)) {
            Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION_M-mingw.zip
            7z x SDL2-devel-$SDL_VERSION_M-mingw.zip -oC:\SDL\
        }
        $env:SDL2_INCLUDE_M = "$SDL_PREFIX_M\include"
        $env:SDL2_LIB_M = "$SDL_PREFIX_M\lib"

    - ps: |
        $SDL_TTF_VERSION_M = "2.0.1"
        $SDL_TTF_PREFIX_M = "C:\SDL\SDL2M_ttf-$SDL_TTF_VERSION"
        if (!(Test-Path -Path $SDL_TTF_PREFIX_M)) {
            Start-FileDownload https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-$SDL_TTF_VERSION_M-mingw.zip
            7z x SDL2_mixer-devel-$SDL_MIXER_VERSION_M-mingw.zip -oC:\SDL\
        }
        $env:SDL2_TTF_INCLUDE_M = "$SDL_TTF_PREFIX_M\include"
        $env:SDL2_TTF_LIB_M = "$SDL_TTF_PREFIX_M\lib"

install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
    - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
    - SET PATH=%PATH%;C:\MinGW\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo test --verbose
    - cargo test --manifest-path wydyd/Cargo.toml --verbose
