sudo: required
dist: trusty
language: rust
cache: cargo
rust:
    - stable
    - beta 
    - nightly
os:
    - linux
    - osx

before_install:
    - ./.travis/before_install.sh

script:
    - cargo test --verbose
    - cargo test --verbose --manifest-path wydyd/Cargo.toml 
    - cargo test --verbose --manifest-path wydy-sdl2/Cargo.toml
