language: rust
cache: cargo
rust:
    - stable
    - beta 
    - nightly
os:
    - linux
    - osx

script:
    - cargo build --verbose
    - cargo build --verbose --manifest-path wydyd/Cargo.toml
    - cargo test --verbose
    - cargo test --verbose --manifest-path wydyd/Cargo.toml 
