[package]
name = "wydyd"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
app_dirs = "*"
clap = "*"
log = "*"
simplelog = "*"
verex = "*"

[dependencies.parser_rs]
git = "https://github.com/notkild/parser_rs"
