[package]
name = "wydyd"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
app_dirs = "*"
clap = "*"
log = "*"
simplelog = "*"
verex = "*"

[dependencies.parser_rs]
path = "/home/notkild/projects/lib/parser_rs"
