[package]
name = "wydyd"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
fern = "*"
log = "*"
time = "*"
verex = "*"

[dependencies.parser_rs]
path = "/home/notkild/projects/lib/parser_rs"

[lib]
name = "libwydyd"
path = "src/lib.rs"
