[package]
name = "wydyd"
version = "0.1.0"
authors = ["notkild <notkild@gmail.com>"]

[dependencies]
verex = {version = "*", optional = true}

[features]
default = []
url-check = ["verex"]
all = ["verex"]

[lib]
name = "libwydyd"
path = "src/lib.rs"
